### PR TITLE
updating cavity status record

### PR DESCRIPTION
**Pull request by lisazacarias**

### CODE REVIEW

**Review by nneveu — APPROVED** [review]
Is this file always updated when the cavities are moved from cold landing to on resonance? And is that info pulled automatically with a script? Maybe this belongs somewhere else if it's more 'data' than code?

**Comment by lisazacarias** [comment]
> Is this file always updated when the cavities are moved from cold landing to on resonance? And is that info pulled automatically with a script? Maybe this belongs somewhere else if it's more 'data' than code?

This is the file we need for catastrophic power outage (the one we referenced at the meeting yesterday). I can't think of anywhere else to put it that isn't hosted on site, and this is the easiest way to get it off production. Do you have ideas?

**Comment by nneveu** [comment]
I've used git-lfs in the past and liked it. 

https://git-lfs.com/
https://stackoverflow.com/questions/35575400/what-is-the-advantage-of-git-lfs

**Comment by nneveu** [comment]
I guess I should add I know this isn't a large file, but would clean up the repo when cloning etc.

**Pull request merged**
